### ISSUE TITLE
winhp

### ISSUE THREAD

**Issue by l337quez** [cchabanois/mesfavoris#100]
Hello friend, I am a user of gnu linux, use the winhp program a lot, I would like to put it at the service of gnu linux users, well if you allow it. I am seeing that it is a GPL license, I would like you to provide me with the code to study it and put a version for Linux. thank you

**Comment by cchabanois-sfdc** [comment]
You can get the source here : https://sourceforge.net/projects/winhp/files/winhp-source/3.51b3/
