### ISSUE TITLE
ClassNotFoundException due to Automated Error Reporting not configured correctly

### ISSUE THREAD

**Issue by JohannesDorn** [cchabanois/mesfavoris#41]
Hi,

I've noticed that mesfavoris is (partially) configured to send error reports to its own Ctrlflow Automated Error Reporting service at https://aer.ctrlflow.com/mesfavoris.

However, due to a missing dependency, the error reporting client (AERI) fails to load with a ClassNotFoundException and no error reports can be sent.

The fix is simple. You only need to add an (optional) dependency on the aeri plugin.
Copy & paste this line to your [MANIFEST.MF](https://github.com/cchabanois/mesfavoris/blob/9233240e018ea2dfd35243fdcb2f70aa2d8d0dfe/bundles/mesfavoris/META-INF/MANIFEST.MF#L66) file:
`org.eclipse.epp.logging.aeri.ide;bundle-version="[2.0.0,3.0.0)";resolution:=optional`

This information can also be found in your error reporting service on the [client configurations](https://aer.ctrlflow.com/mesfavoris/reviewers#!/client-configurations) page.

Note that I am one of the developers of Automated Error Reporting. Thanks for using our software :)

**Comment by cchabanois** [comment]
Fixed with commit ad0e80f507b5e9c14c4f9d2b777e75d901e8c2a6
Thanks for reporting the issue !
