### ISSUE TITLE
Bookmark related lines of code or multiple lines of code

### ISSUE THREAD

**Issue by NovaViper** [cchabanois/mesfavoris#78]
I'm working on a Minecraft mod project where one of the devs working on it have added in some code at different places in the class. I wish there was a way to mark both of those lines within the same bookmark since they are related to a new feature.

**Comment by cchabanois** [comment]
What would be the expected behavior when you double-click on this bookmark ?
Note that you can create a folder and put your related bookmarks in it. Does it fit your needs ?
