### ISSUE TITLE
Eclipse hangs frequently.

### ISSUE THREAD

**Issue by biswajit-goswami** [cchabanois/mesfavoris#83]
When typing the comments for a bookmark, often eclipse freezes. Restart is the only option.
Sometimes it is less frequent, sometimes more.
Seems it happens when I type too fast, and it tries to save every letter..and gets hung??
OS : Windows 10
Oxygen.2 Release (4.7.2)
Plugin version: 2.0.0.v20180419-2055
Thanks a lot.

**Comment by cchabanois** [comment]
weird ... I don't have this behavior but I don't test very often on Windows. The bookmarks file is supposed to be saved after 2 seconds of inactivity after a change.
Unfortunately, windows is not supported by our CI environment (Travis). I will need to create a VM and test myself.

**Comment by biswajit-goswami** [comment]
Hi,
Is there a way to increase the save interval- from 2 seconds to something longer?
Regards,
Biswajit

**Comment by mbinyon** [comment]
Hi, great tool but experiencing this issue including
"Seems it happens when I type too fast, and it tries to save every letter..and gets hung??"

**Comment by cchabanois** [comment]
Should be fixed with #130
