### ISSUE TITLE
bookmarks in root folder are not synchronized to GDrive

### ISSUE THREAD

**Issue by thomasrebele** [cchabanois/mesfavoris#99]
The bookmarks that are created directly in the "default" folder do not appear in the GDrive folder.

Workaround: 
1. create a bookmark folder
2. add it to GDrive
3. add a bookmark, and move it to that folder
4. future bookmarks seem to be added to this folder (maybe an option for changing the default folder would be helpful?)

Background story: I previously lost my Eclipse bookmarks after checking out a new version of the project with SVN. Then I discovered mesfavoris, and decided to synchronize with GDrive to keep a backup of my bookmarks. Awesome plugin!

**Comment by cchabanois** [comment]
When a bookmark is created, it is added in the bookmark folder selected in the "Mes Favoris" view.
If none, it is added in the default folder.
